name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile Java files
        run: |
          mkdir -p target/classes
          find . -name "*.java" > sources.txt
          javac -d target/classes -cp . @sources.txt

      - name: Test compilation
        run: |
          echo "=== Classes compiladas ==="
          find target/classes -name "*.class"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: java-classes
          path: target/classes/

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t calculadora:latest .

      - name: Test Docker image
        run: |
          docker images | grep calculadora

      - name: Save Docker image
        run: |
          docker save calculadora:latest > calculadora.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: calculadora.tar

  deploy:
    needs: [build, docker]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          docker load < calculadora.tar

      - name: Deploy (simulation)
        run: |
          echo "=== Deploy simulado ==="
          echo "Docker image carregada e pronta para deploy"
          docker images | grep calculadora